# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/form.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(630, 781)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.sliderViewPosZ = QtWidgets.QSlider(self.groupBox)
        self.sliderViewPosZ.setProperty("value", 90)
        self.sliderViewPosZ.setOrientation(QtCore.Qt.Horizontal)
        self.sliderViewPosZ.setObjectName("sliderViewPosZ")
        self.gridLayout.addWidget(self.sliderViewPosZ, 2, 1, 1, 1)
        self.sliderViewPosX = QtWidgets.QSlider(self.groupBox)
        self.sliderViewPosX.setProperty("value", 63)
        self.sliderViewPosX.setOrientation(QtCore.Qt.Horizontal)
        self.sliderViewPosX.setObjectName("sliderViewPosX")
        self.gridLayout.addWidget(self.sliderViewPosX, 0, 1, 1, 1)
        self.sliderViewPosY = QtWidgets.QSlider(self.groupBox)
        self.sliderViewPosY.setProperty("value", 60)
        self.sliderViewPosY.setOrientation(QtCore.Qt.Horizontal)
        self.sliderViewPosY.setObjectName("sliderViewPosY")
        self.gridLayout.addWidget(self.sliderViewPosY, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sliderLightPosY = QtWidgets.QSlider(self.groupBox_2)
        self.sliderLightPosY.setOrientation(QtCore.Qt.Horizontal)
        self.sliderLightPosY.setObjectName("sliderLightPosY")
        self.gridLayout_2.addWidget(self.sliderLightPosY, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.sliderLightPosZ = QtWidgets.QSlider(self.groupBox_2)
        self.sliderLightPosZ.setOrientation(QtCore.Qt.Horizontal)
        self.sliderLightPosZ.setObjectName("sliderLightPosZ")
        self.gridLayout_2.addWidget(self.sliderLightPosZ, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.sliderLightPosX = QtWidgets.QSlider(self.groupBox_2)
        self.sliderLightPosX.setOrientation(QtCore.Qt.Horizontal)
        self.sliderLightPosX.setObjectName("sliderLightPosX")
        self.gridLayout_2.addWidget(self.sliderLightPosX, 0, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.sliderLightIntensive = QtWidgets.QSlider(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderLightIntensive.sizePolicy().hasHeightForWidth())
        self.sliderLightIntensive.setSizePolicy(sizePolicy)
        self.sliderLightIntensive.setMinimumSize(QtCore.QSize(200, 0))
        self.sliderLightIntensive.setProperty("value", 99)
        self.sliderLightIntensive.setOrientation(QtCore.Qt.Horizontal)
        self.sliderLightIntensive.setObjectName("sliderLightIntensive")
        self.verticalLayout_12.addWidget(self.sliderLightIntensive)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.comboBoxStyle = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxStyle.sizePolicy().hasHeightForWidth())
        self.comboBoxStyle.setSizePolicy(sizePolicy)
        self.comboBoxStyle.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBoxStyle.setObjectName("comboBoxStyle")
        self.comboBoxStyle.addItem("")
        self.comboBoxStyle.addItem("")
        self.comboBoxStyle.addItem("")
        self.verticalLayout_10.addWidget(self.comboBoxStyle)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.verticalLayout_9.addWidget(self.groupBox_4)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.comboBoxTexture = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxTexture.sizePolicy().hasHeightForWidth())
        self.comboBoxTexture.setSizePolicy(sizePolicy)
        self.comboBoxTexture.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBoxTexture.setObjectName("comboBoxTexture")
        self.comboBoxTexture.addItem("")
        self.comboBoxTexture.addItem("")
        self.comboBoxTexture.addItem("")
        self.comboBoxTexture.addItem("")
        self.comboBoxTexture.addItem("")
        self.verticalLayout_15.addWidget(self.comboBoxTexture)
        self.horizontalLayout_2.addLayout(self.verticalLayout_15)
        self.verticalLayout_14.addWidget(self.groupBox_5)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton.setMinimumSize(QtCore.QSize(250, 0))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_16.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_2.setMinimumSize(QtCore.QSize(250, 0))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_16.addWidget(self.pushButton_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_16)
        self.verticalLayout_14.addWidget(self.groupBox_7)
        self.verticalLayout_9.addLayout(self.verticalLayout_14)
        self.verticalLayout.addLayout(self.verticalLayout_9)
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_8)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(50)
        self.spinBox.setProperty("value", 5)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_17.addWidget(self.spinBox)
        self.horizontalLayout_6.addLayout(self.verticalLayout_17)
        self.verticalLayout.addWidget(self.groupBox_8)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.check1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check1.setObjectName("check1")
        self.verticalLayout.addWidget(self.check1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.widget_layout = QtWidgets.QVBoxLayout()
        self.widget_layout.setObjectName("widget_layout")
        self.horizontalLayout.addLayout(self.widget_layout)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Курсовая работа"))
        self.groupBox.setTitle(_translate("MainWindow", "Положение наблюдателя"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">X</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Y</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Z</p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Положение источника света"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">X</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Z</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Y</p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Интенсивность"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Отрисовка"))
        self.comboBoxStyle.setItemText(0, _translate("MainWindow", "GL_FILL"))
        self.comboBoxStyle.setItemText(1, _translate("MainWindow", "GL_LINE"))
        self.comboBoxStyle.setItemText(2, _translate("MainWindow", "GL_POINT"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Текстура"))
        self.comboBoxTexture.setItemText(0, _translate("MainWindow", "дерево"))
        self.comboBoxTexture.setItemText(1, _translate("MainWindow", "камень"))
        self.comboBoxTexture.setItemText(2, _translate("MainWindow", "асфальт"))
        self.comboBoxTexture.setItemText(3, _translate("MainWindow", "кирпич"))
        self.comboBoxTexture.setItemText(4, _translate("MainWindow", "без текстуры"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Цвет"))
        self.pushButton.setText(_translate("MainWindow", "Произвольный цвет"))
        self.pushButton_2.setText(_translate("MainWindow", "Без цвета"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Количество ступенек"))
        self.check1.setText(_translate("MainWindow", "Режим камеры"))


